version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    # change to some generic circleci images
    - image: vuejs/ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      # reduce size of cache
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run: echo "install dependencies"
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue

  lint-flow-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run linting tests"

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run coverage tests"
      - run:
        # let's leave this but simplify
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             ./node_modules/.bin/codecov
           fi

  test-e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run end to end tests"

  test-ssr-weex:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run some ssr tests?"

  trigger-regression-test:
    <<: *defaults
    steps:
      - run:
          name: regression testing
          command: |
            echo "cool done"

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cover:
          requires:
            - install
      - lint-flow-types:
          requires:
            - install
      - test-e2e:
          requires:
            - install
      - test-ssr-weex:
          requires:
            - install
      - trigger-regression-test:
          filters:
            branches:
              only:
                - "2.6"
                - regression-test
          requires:
            - test-cover
            - lint-flow-types
            - test-e2e
            - test-ssr-weex
# yeah let's not do the cron
  # weekly_regression_test:
  #   triggers:
  #     - schedule:
  #         # At 13:00 UTC (9:00 EDT) on every Monday
  #         cron: "0 13 * * 1"
  #         filters:
  #           branches:
  #             only:
  #               dev
  #   jobs:
  #     - install
  #     - test-cover:
  #         requires:
  #           - install
  #     - lint-flow-types:
  #         requires:
  #           - install
  #     - test-e2e:
  #         requires:
  #           - install
  #     - test-ssr-weex:
  #         requires:
  #           - install
  #     - trigger-regression-test:
  #         requires:
  #           - test-cover
  #           - lint-flow-types
  #           - test-e2e
  #           - test-ssr-weex
